/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://i5fqmh6tvzbb3itdmgfjjumvse.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-zm65crltn5hanmrm3t4chnzlku",
    "aws_cognito_identity_pool_id": "us-east-1:2c93fa2c-723a-43c2-8f33-a286827a839e",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_7VKhJxfHw",
    "aws_user_pools_web_client_id": "1lqm9tc0a3vpl02q7fvdjsbmcr",
    "oauth": {}
};


export default awsmobile;
